# Name of the workflow, visible in the GitHub Actions tab
name: Hello World Workflow

# Controls when the workflow is triggered.
# This runs the workflow when someone pushes code to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs.
jobs:
  # This defines a job named "say-hello".
  say-hello:
    # The type of machine (runner) the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # A step to run a single command.
      - name: Run a simple "Hello, world!" script
        run: echo "Hello, world!"
